name: "Continuous Integration"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: "Build code"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout sources"
        uses: actions/checkout@v4

      - name: "Set up GraalVM"
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: 'gradle'

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false

      - name: "Setup SSH"
        run: |
          mkdir -p ~/.ssh
          cat .github/files/known_hosts > ~/.ssh/known_hosts
          echo "${bot_devex_ssh_private_key_rsa}" > ~/.ssh/id_rsa
          echo "${bot_devex_ssh_private_key_ed25519}" > ~/.ssh/id_ed25519

          cat << EOF > ~/.ssh/config
          Host gitlab.com
            IdentityFile ~/.ssh/id_ed25519

          Host github.com
            IdentityFile ~/.ssh/id_rsa
          EOF

          chmod -R 500 ~/.ssh
        env:
          bot_devex_ssh_private_key_rsa: ${{ secrets.BOT_DEVEX_SSH_PRIVATE_KEY_RSA }}
          bot_devex_ssh_private_key_ed25519: ${{ secrets.BOT_DEVEX_SSH_PRIVATE_KEY_ED25519 }}

      - name: "Gradle build"
        run: ./gradlew build
        env:
          GITLAB_TOKEN: ${{ secrets.BOT_GITLAB_TOKEN_READ_API }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN_READ_ORG_AND_REPO }}
          DEVEX_SSH_INTEGRATION_TESTS: "true"

      - name: "Upload Test Reports"
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: build/reports/tests
          retention-days: 5

      - name: "Publish Unit Test Results"
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/test-results/test/*.xml

      - name: "Build native image"
        run: ./gradlew nativeCompile
        env:
          GITLAB_TOKEN: ${{ secrets.BOT_GITLAB_TOKEN_READ_API }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN_READ_ORG_AND_REPO }}

      - name: "Run and test native binary"
        run: .github/scripts/run-native-binary.sh
        env:
          GITLAB_TOKEN: ${{ secrets.BOT_GITLAB_TOKEN_READ_API }}
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN_READ_ORG_AND_REPO }}

      - name: "Clean up"
        if: ${{ always() }}
        run: sudo rm -rf ~/.ssh
